In [1]:
import garminconnect
from datetime import date

In [2]:
from getpass import getpass

email = input("Enter email address: ")
password = getpass("Enter password: ")

garmin = garminconnect.Garmin(email, password)
garmin.login()

garmin.display_name

Enter email address: adham.arif@gmail.com
Enter password: ········

'ccf2cb2d-d84c-45b4-bebd-7362690d2483'

In [3]:
import os

# retrieve the value of the GARTH_HOME environment variable 
# (defaulting to ~/.garth if not set) and then uses the 
# garmin.garth.dump function to process that path.

GARTH_HOME = os.getenv("GARTH_HOME", "~/.garth")
garmin.garth.dump(GARTH_HOME)

# Get Connect stats

In [5]:
from datetime import date, timedelta
import pandas as pd

# Define your target end date
end_date = date(2023, 10, 30)

# Calculate the start date as 2 weeks (14 days) before the end date
start_date = end_date - timedelta(days=14)

datelist = []

current_date = start_date
while current_date <= end_date:
    datelist.append(current_date)
    current_date += timedelta(days=1)

datelist_new = [x.isoformat() for x in datelist]

dataframes_list = []  # List to store each day's DataFrame

for day in datelist_new:
    current_entry = garmin.get_sleep_data(day)
    current_entry_df = pd.DataFrame([current_entry])  # Convert the dictionary to a DataFrame
    dataframes_list.append(current_entry_df)

# Concatenate all the DataFrames in the list
week_sleep_df = pd.concat(dataframes_list, ignore_index=True)

week_sleep_df

,dailySleepDTO,sleepMovement,remSleepData,sleepLevels,sleepRestlessMoments,restlessMomentsCount,wellnessEpochRespirationDataDTOList,sleepHeartRate,sleepStress,sleepBodyBattery,hrvData,avgOvernightHrv,hrvStatus,restingHeartRate
0,"{'id': None, 'userProfilePK': 116790105, 'cale...",[],None,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'id': 1697503980000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-16T23:53:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-17T00:53:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1697504160000}, {'va...",44.0,"[{'startTimeGMT': 1697503980000, 'respirationV...","[{'value': 54, 'startGMT': 1697503920000}, {'v...","[{'value': 12, 'startGMT': 1697503860000}, {'v...","[{'value': 12, 'startGMT': 1697503860000}, {'v...","[{'value': 53.0, 'startGMT': 1697504127000}, {...",62.0,NONE,50.0
2,"{'id': 1697589060000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-17T23:31:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-18T00:31:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1697589060000}, {'va...",41.0,"[{'startTimeGMT': 1697589060000, 'respirationV...","[{'value': 54, 'startGMT': 1697589000000}, {'v...","[{'value': 12, 'startGMT': 1697589000000}, {'v...","[{'value': 13, 'startGMT': 1697589000000}, {'v...","[{'value': 59.0, 'startGMT': 1697589327000}, {...",66.0,NONE,50.0
3,"{'id': 1697678700000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-19T00:25:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-19T01:25:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1697679060000}, {'va...",31.0,"[{'startTimeGMT': 1697678700000, 'respirationV...","[{'value': 50, 'startGMT': 1697678640000}, {'v...","[{'value': 6, 'startGMT': 1697678640000}, {'va...","[{'value': 26, 'startGMT': 1697678640000}, {'v...","[{'value': 66.0, 'startGMT': 1697678727000}, {...",69.0,NONE,51.0
4,"{'id': 1697759820000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-19T22:57:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-19T23:57:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1697760180000}, {'va...",42.0,"[{'startTimeGMT': 1697759820000, 'respirationV...","[{'value': 61, 'startGMT': 1697759760000}, {'v...","[{'value': 11, 'startGMT': 1697759640000}, {'v...","[{'value': 5, 'startGMT': 1697759640000}, {'va...","[{'value': 54.0, 'startGMT': 1697760027000}, {...",63.0,NONE,52.0
5,"{'id': 1697848380000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-20T23:33:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-21T00:33:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1697850360000}, {'va...",32.0,"[{'startTimeGMT': 1697848380000, 'respirationV...","[{'value': 56, 'startGMT': 1697848320000}, {'v...","[{'value': 11, 'startGMT': 1697848200000}, {'v...","[{'value': 19, 'startGMT': 1697848200000}, {'v...","[{'value': 70.0, 'startGMT': 1697848527000}, {...",63.0,NONE,49.0
6,"{'id': 1697944320000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-22T02:12:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-22T03:12:00.0', 'endGMT...","[{'value': 2, 'startGMT': 1697946120000}, {'va...",40.0,"[{'startTimeGMT': 1697944320000, 'respirationV...","[{'value': 57, 'startGMT': 1697944320000}, {'v...","[{'value': 11, 'startGMT': 1697944140000}, {'v...","[{'value': 9, 'startGMT': 1697944140000}, {'va...","[{'value': 66.0, 'startGMT': 1697944527000}, {...",63.0,NONE,49.0
7,"{'id': 1698020640000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-22T23:24:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-23T00:24:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698020820000}, {'va...",39.0,"[{'startTimeGMT': 1698020640000, 'respirationV...","[{'value': 54, 'startGMT': 1698020640000}, {'v...","[{'value': 10, 'startGMT': 1698020460000}, {'v...","[{'value': 13, 'startGMT': 1698020460000}, {'v...","[{'value': 67.0, 'startGMT': 1698020727000}, {...",75.0,NONE,48.0
8,"{'id': 1698108720000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-23T23:52:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-24T00:52:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698108900000}, {'va...",64.0,"[{'startTimeGMT': 1698108720000, 'respirationV...","[{'value': 50, 'startGMT': 1698108720000}, {'v...","[{'value': 6, 'startGMT': 1698108660000}, {'va...","[{'value': 31, 'startGMT': 1698108660000}, {'v...","[{'value': 83.0, 'startGMT': 1698108927000}, {...",74.0,NONE,49.0
9,"{'id': 1698192420000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-24T23:07:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-25T00:07:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698193500000}, {'va...",24.0,"[{'startTimeGMT': 1698192420000, 'respirationV...","[{'value': 60, 'startGMT': 1698192360000}, {'v...","[{'value': 19, 'startGMT': 1698192360000}, {'v...","[{'value': 29, 'startGMT': 1698192360000}, {'v...","[{'value': 58.0, 'startGMT': 1698192628000}, {...",67.0,NONE,50.0
10,"{'id': 1698280740000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-25T23:39:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-26T00:39:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698281100000}, {'va...",46.0,"[{'startTimeGMT': 1698280740000, 'respirationV...","[{'value': 52, 'startGMT': 1698280680000}, {'v...","[{'value': 2, 'startGMT': 1698280560000}, {'va...","[{'value': 18, 'startGMT': 1698280560000}, {'v...","[{'value': 81.0, 'startGMT': 1698280829000}, {...",65.0,NONE,49.0
11,"{'id': 1698368220000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-26T23:57:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-27T00:57:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698368400000}, {'va...",50.0,"[{'startTimeGMT': 1698368220000, 'respirationV...","[{'value': 53, 'startGMT': 1698368160000}, {'v...","[{'value': 6, 'startGMT': 1698368040000}, {'va...","[{'value': 16, 'startGMT': 1698368040000}, {'v...","[{'value': 87.0, 'startGMT': 1698368429000}, {...",66.0,NONE,50.0
12,"{'id': 1698456060000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-28T00:21:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-28T01:21:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698456600000}, {'va...",59.0,"[{'startTimeGMT': 1698456060000, 'respirationV...","[{'value': 68, 'startGMT': 1698456000000}, {'v...","[{'value': 28, 'startGMT': 1698455880000}, {'v...","[{'value': 10, 'startGMT': 1698455880000}, {'v...","[{'value': 55.0, 'startGMT': 1698456329000}, {...",65.0,NONE,51.0
13,"{'id': 1698542340000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-29T00:19:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-29T01:19:00.0', 'endGMT...","[{'value': 1, 'startGMT': 1698548640000}, {'va...",39.0,"[{'startTimeGMT': 1698542340000, 'respirationV...","[{'value': 58, 'startGMT': 1698542280000}, {'v...","[{'value': 15, 'startGMT': 1698542280000}, {'v...","[{'value': 39, 'startGMT': 1698542280000}, {'v...","[{'value': 56.0, 'startGMT': 1698542428000}, {...",62.0,NONE,51.0
14,"{'id': 1698628920000, 'userProfilePK': 1167901...","[{'startGMT': '2023-10-30T00:22:00.0', 'endGMT...",True,"[{'startGMT': '2023-10-30T01:22:00.0', 'endGMT...","[{'value': 2, 'startGMT': 1698631440000}, {'va...",45.0,"[{'startTimeGMT': 1698628920000, 'respirationV...","[{'value': 58, 'startGMT': 1698628920000}, {'v...","[{'value': 15, 'startGMT': 1698628860000}, {'v...","[{'value': 19, 'startGMT': 1698628860000}, {'v...","[{'value': 65.0, 'startGMT': 1698629128000}, {...",66.0,NONE,48.0

In [67]:
week_sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   dailySleepDTO                        15 non-null     object
 1   sleepMovement                        15 non-null     object
 2   remSleepData                         13 non-null     object
 3   sleepLevels                          15 non-null     object
 4   sleepRestlessMoments                 13 non-null     object
 5   restlessMomentsCount                 13 non-null     float64
 6   wellnessEpochRespirationDataDTOList  13 non-null     object
 7   sleepHeartRate                       13 non-null     object
 8   sleepStress                          13 non-null     object
 9   sleepBodyBattery                     13 non-null     object
 10  hrvData                              13 non-null     object
 11  avgOvernightHrv                      13 non-null     float64
 12  hrvStatus                            13 non-null     object
 13  restingHeartRate                     13 non-null     float64
dtypes: float64(3), object(11)
memory usage: 1.8+ KB

In [42]:
week_sleep_df.columns

Index(['dailySleepDTO', 'sleepMovement', 'remSleepData', 'sleepLevels',
       'sleepRestlessMoments', 'restlessMomentsCount',
       'wellnessEpochRespirationDataDTOList', 'sleepHeartRate', 'sleepStress',
       'sleepBodyBattery', 'hrvData', 'avgOvernightHrv', 'hrvStatus',
       'restingHeartRate'],
      dtype='object')

json_data = garmin.get_sleep_data(day)

from pandas import json_normalize

# Assuming you have the data in the variable named json_data
flattened_data = json_normalize(json_data)

# Convert the flattened data into a dataframe
df = pd.DataFrame(flattened_data)
df

# Exploring the columns

In [6]:
expanded_df = pd.json_normalize(week_sleep_df['dailySleepDTO'])

# If you want to remove the "dailySleepDTO." prefix from the column names:
expanded_df.columns = [col.replace('dailySleepDTO.', '') for col in expanded_df.columns]

expanded_df

,id,userProfilePK,calendarDate,sleepTimeSeconds,napTimeSeconds,sleepWindowConfirmed,sleepWindowConfirmationType,sleepStartTimestampGMT,sleepEndTimestampGMT,sleepStartTimestampLocal,...,sleepScores.lightPercentage.optimalStart,sleepScores.lightPercentage.optimalEnd,sleepScores.lightPercentage.idealStartInSeconds,sleepScores.lightPercentage.idealEndInSeconds,sleepScores.deepPercentage.value,sleepScores.deepPercentage.qualifierKey,sleepScores.deepPercentage.optimalStart,sleepScores.deepPercentage.optimalEnd,sleepScores.deepPercentage.idealStartInSeconds,sleepScores.deepPercentage.idealEndInSeconds
0,NaN,116790105,2023-10-16,NaN,NaN,None,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.697504e+12,116790105,2023-10-17,21300.0,0.0,True,enhanced_confirmed_final,1.697504e+12,1.697526e+12,1.697511e+12,...,30.0,64.0,6390.0,13632.0,19.0,EXCELLENT,16.0,33.0,3408.0,7029.0
2,1.697589e+12,116790105,2023-10-18,21900.0,0.0,True,enhanced_confirmed_final,1.697589e+12,1.697616e+12,1.697596e+12,...,30.0,64.0,6570.0,14016.0,22.0,EXCELLENT,16.0,33.0,3504.0,7227.0
3,1.697679e+12,116790105,2023-10-19,16560.0,0.0,True,enhanced_confirmed_final,1.697679e+12,1.697697e+12,1.697686e+12,...,30.0,64.0,4968.0,10598.4,38.0,EXCELLENT,16.0,33.0,2649.6,5464.8
4,1.697760e+12,116790105,2023-10-20,25920.0,0.0,True,enhanced_confirmed_final,1.697760e+12,1.697789e+12,1.697767e+12,...,30.0,64.0,7776.0,16588.8,22.0,EXCELLENT,16.0,33.0,4147.2,8553.6
5,1.697848e+12,116790105,2023-10-21,20640.0,0.0,True,enhanced_confirmed_final,1.697848e+12,1.697869e+12,1.697856e+12,...,30.0,64.0,6192.0,13209.6,25.0,EXCELLENT,16.0,33.0,3302.4,6811.2
6,1.697944e+12,116790105,2023-10-22,18420.0,0.0,True,enhanced_confirmed_final,1.697944e+12,1.697965e+12,1.697952e+12,...,30.0,64.0,5526.0,11788.8,20.0,EXCELLENT,16.0,33.0,2947.2,6078.6
7,1.698021e+12,116790105,2023-10-23,21660.0,0.0,True,enhanced_confirmed_final,1.698021e+12,1.698043e+12,1.698028e+12,...,30.0,64.0,6498.0,13862.4,31.0,EXCELLENT,16.0,33.0,3465.6,7147.8
8,1.698109e+12,116790105,2023-10-24,31980.0,0.0,True,enhanced_confirmed_final,1.698109e+12,1.698142e+12,1.698116e+12,...,30.0,64.0,9594.0,20467.2,18.0,EXCELLENT,16.0,33.0,5116.8,10553.4
9,1.698192e+12,116790105,2023-10-25,14700.0,0.0,True,enhanced_confirmed_final,1.698192e+12,1.698209e+12,1.698200e+12,...,30.0,64.0,4410.0,9408.0,39.0,EXCELLENT,16.0,33.0,2352.0,4851.0
10,1.698281e+12,116790105,2023-10-26,22020.0,0.0,True,enhanced_confirmed_final,1.698281e+12,1.698303e+12,1.698288e+12,...,30.0,64.0,6606.0,14092.8,13.0,FAIR,16.0,33.0,3523.2,7266.6
11,1.698368e+12,116790105,2023-10-27,25260.0,0.0,True,enhanced_confirmed_final,1.698368e+12,1.698396e+12,1.698375e+12,...,30.0,64.0,7578.0,16166.4,20.0,EXCELLENT,16.0,33.0,4041.6,8335.8
12,1.698456e+12,116790105,2023-10-28,31620.0,0.0,True,enhanced_confirmed_final,1.698456e+12,1.698491e+12,1.698463e+12,...,30.0,64.0,9486.0,20236.8,16.0,FAIR,16.0,33.0,5059.2,10434.6
13,1.698542e+12,116790105,2023-10-29,27780.0,0.0,True,enhanced_confirmed_final,1.698542e+12,1.698571e+12,1.698546e+12,...,30.0,64.0,8334.0,17779.2,19.0,EXCELLENT,16.0,33.0,4444.8,9167.4
14,1.698629e+12,116790105,2023-10-30,29940.0,0.0,True,enhanced_confirmed_final,1.698629e+12,1.698660e+12,1.698633e+12,...,30.0,64.0,8982.0,19161.6,20.0,EXCELLENT,16.0,33.0,4790.4,9880.2

In [44]:
expanded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 65 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   id                                               4 non-null      int64
 1   userProfilePK                                    4 non-null      int64
 2   calendarDate                                     4 non-null      object
 3   sleepTimeSeconds                                 4 non-null      int64
 4   napTimeSeconds                                   4 non-null      int64
 5   sleepWindowConfirmed                             4 non-null      bool
 6   sleepWindowConfirmationType                      4 non-null      object
 7   sleepStartTimestampGMT                           4 non-null      int64
 8   sleepEndTimestampGMT                             4 non-null      int64
 9   sleepStartTimestampLocal                         4 non-null      int64
 10  sleepEndTimestampLocal                           4 non-null      int64
 11  autoSleepStartTimestampGMT                       0 non-null      object
 12  autoSleepEndTimestampGMT                         0 non-null      object
 13  sleepQualityTypePK                               0 non-null      object
 14  sleepResultTypePK                                0 non-null      object
 15  unmeasurableSleepSeconds                         4 non-null      int64
 16  deepSleepSeconds                                 4 non-null      int64
 17  lightSleepSeconds                                4 non-null      int64
 18  remSleepSeconds                                  4 non-null      int64
 19  awakeSleepSeconds                                4 non-null      int64
 20  deviceRemCapable                                 4 non-null      bool
 21  retro                                            4 non-null      bool
 22  sleepFromDevice                                  4 non-null      bool
 23  averageRespirationValue                          4 non-null      float64
 24  lowestRespirationValue                           4 non-null      float64
 25  highestRespirationValue                          4 non-null      float64
 26  awakeCount                                       4 non-null      int64
 27  avgSleepStress                                   4 non-null      float64
 28  ageGroup                                         4 non-null      object
 29  sleepScoreFeedback                               4 non-null      object
 30  sleepScoreInsight                                4 non-null      object
 31  sleepScorePersonalizedInsight                    4 non-null      object
 32  sleepVersion                                     4 non-null      int64
 33  sleepScores.totalDuration.qualifierKey           4 non-null      object
 34  sleepScores.totalDuration.optimalStart           4 non-null      float64
 35  sleepScores.totalDuration.optimalEnd             4 non-null      float64
 36  sleepScores.stress.qualifierKey                  4 non-null      object
 37  sleepScores.stress.optimalStart                  4 non-null      float64
 38  sleepScores.stress.optimalEnd                    4 non-null      float64
 39  sleepScores.awakeCount.qualifierKey              4 non-null      object
 40  sleepScores.awakeCount.optimalStart              4 non-null      float64
 41  sleepScores.awakeCount.optimalEnd                4 non-null      float64
 42  sleepScores.overall.value                        4 non-null      int64
 43  sleepScores.overall.qualifierKey                 4 non-null      object
 44  sleepScores.remPercentage.value                  4 non-null      int64
 45  sleepScores.remPercentage.qualifierKey           4 non-null      object
 46  sleepScores.remPercentage.optimalStart           4 non-null      float64
 47  sleepScores.remPercentage.optimalEnd             4 non-null      float64
 48  sleepScores.remPercentage.idealStartInSeconds    4 non-null      float64
 49  sleepScores.remPercentage.idealEndInSeconds      4 non-null      float64
 50  sleepScores.restlessness.qualifierKey            4 non-null      object
 51  sleepScores.restlessness.optimalStart            4 non-null      float64
 52  sleepScores.restlessness.optimalEnd              4 non-null      float64
 53  sleepScores.lightPercentage.value                4 non-null      int64
 54  sleepScores.lightPercentage.qualifierKey         4 non-null      object
 55  sleepScores.lightPercentage.optimalStart         4 non-null      float64
 56  sleepScores.lightPercentage.optimalEnd           4 non-null      float64
 57  sleepScores.lightPercentage.idealStartInSeconds  4 non-null      float64
 58  sleepScores.lightPercentage.idealEndInSeconds    4 non-null      float64
 59  sleepScores.deepPercentage.value                 4 non-null      int64
 60  sleepScores.deepPercentage.qualifierKey          4 non-null      object
 61  sleepScores.deepPercentage.optimalStart          4 non-null      float64
 62  sleepScores.deepPercentage.optimalEnd            4 non-null      float64
 63  sleepScores.deepPercentage.idealStartInSeconds   4 non-null      float64
 64  sleepScores.deepPercentage.idealEndInSeconds     4 non-null      float64
dtypes: bool(4), float64(24), int64(19), object(18)
memory usage: 2.1+ KB

In [45]:
expanded_df["sleepScores.overall.value"]

0    77
1    74
2    91
3    94
Name: sleepScores.overall.value, dtype: int64

In [46]:
expanded_df["sleepScores.deepPercentage.value"]

0    20
1    16
2    19
3    20
Name: sleepScores.deepPercentage.value, dtype: int64

## Data Inspection

### hrvData

In [72]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['hrvData']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

     value       startGMT
0     87.0  1698368429000
1     75.0  1698368729000
2     72.0  1698369029000
3     70.0  1698369329000
4     71.0  1698369629000
..     ...            ...
399   65.0  1698658228000
400   67.0  1698658528000
401   68.0  1698658828000
402   52.0  1698659128000
403   48.0  1698659428000

[404 rows x 2 columns]

In [73]:
import datetime
full_df['Real Time'] = [datetime.datetime.fromtimestamp(i) for i in full_df["startGMT"] / 1000]
full_df

     value       startGMT           Real Time
0     87.0  1698368429000 2023-10-27 03:00:29
1     75.0  1698368729000 2023-10-27 03:05:29
2     72.0  1698369029000 2023-10-27 03:10:29
3     70.0  1698369329000 2023-10-27 03:15:29
4     71.0  1698369629000 2023-10-27 03:20:29
..     ...            ...                 ...
399   65.0  1698658228000 2023-10-30 10:30:28
400   67.0  1698658528000 2023-10-30 10:35:28
401   68.0  1698658828000 2023-10-30 10:40:28
402   52.0  1698659128000 2023-10-30 10:45:28
403   48.0  1698659428000 2023-10-30 10:50:28

[404 rows x 3 columns]

Time interval: 5 min for every value

In [74]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   value      404 non-null    float64
 1   startGMT   404 non-null    int64
 2   Real Time  404 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 9.6 KB

In [55]:
week_sleep_df['hrvData'][3]

[{'value': 65.0, 'startGMT': 1698629128000},
 {'value': 58.0, 'startGMT': 1698629428000},
 {'value': 61.0, 'startGMT': 1698629728000},
 {'value': 60.0, 'startGMT': 1698630028000},
 {'value': 57.0, 'startGMT': 1698630328000},
 {'value': 61.0, 'startGMT': 1698630628000},
 {'value': 60.0, 'startGMT': 1698630928000},
 {'value': 59.0, 'startGMT': 1698631228000},
 {'value': 59.0, 'startGMT': 1698631528000},
 {'value': 58.0, 'startGMT': 1698631828000},
 {'value': 58.0, 'startGMT': 1698632128000},
 {'value': 50.0, 'startGMT': 1698632428000},
 {'value': 51.0, 'startGMT': 1698632728000},
 {'value': 44.0, 'startGMT': 1698633028000},
 {'value': 49.0, 'startGMT': 1698633328000},
 {'value': 55.0, 'startGMT': 1698633628000},
 {'value': 54.0, 'startGMT': 1698633928000},
 {'value': 63.0, 'startGMT': 1698634228000},
 {'value': 64.0, 'startGMT': 1698634528000},
 {'value': 65.0, 'startGMT': 1698634828000},
 {'value': 75.0, 'startGMT': 1698635128000},
 {'value': 72.0, 'startGMT': 1698635428000},
 {'value': 82.0, 'startGMT': 1698635728000},
 {'value': 71.0, 'startGMT': 1698636028000},
 {'value': 66.0, 'startGMT': 1698636328000},
 {'value': 68.0, 'startGMT': 1698636628000},
 {'value': 67.0, 'startGMT': 1698636928000},
 {'value': 72.0, 'startGMT': 1698637228000},
 {'value': 67.0, 'startGMT': 1698637528000},
 {'value': 63.0, 'startGMT': 1698637828000},
 {'value': 70.0, 'startGMT': 1698638128000},
 {'value': 76.0, 'startGMT': 1698638428000},
 {'value': 75.0, 'startGMT': 1698638728000},
 {'value': 44.0, 'startGMT': 1698639028000},
 {'value': 49.0, 'startGMT': 1698639328000},
 {'value': 74.0, 'startGMT': 1698639628000},
 {'value': 58.0, 'startGMT': 1698639928000},
 {'value': 60.0, 'startGMT': 1698640228000},
 {'value': 65.0, 'startGMT': 1698640528000},
 {'value': 62.0, 'startGMT': 1698640828000},
 {'value': 59.0, 'startGMT': 1698641128000},
 {'value': 68.0, 'startGMT': 1698641428000},
 {'value': 62.0, 'startGMT': 1698641728000},
 {'value': 66.0, 'startGMT': 1698642028000},
 {'value': 88.0, 'startGMT': 1698642328000},
 {'value': 86.0, 'startGMT': 1698642628000},
 {'value': 72.0, 'startGMT': 1698642928000},
 {'value': 68.0, 'startGMT': 1698643228000},
 {'value': 66.0, 'startGMT': 1698643528000},
 {'value': 74.0, 'startGMT': 1698643828000},
 {'value': 88.0, 'startGMT': 1698644128000},
 {'value': 51.0, 'startGMT': 1698644428000},
 {'value': 44.0, 'startGMT': 1698644728000},
 {'value': 43.0, 'startGMT': 1698645028000},
 {'value': 60.0, 'startGMT': 1698645328000},
 {'value': 70.0, 'startGMT': 1698645628000},
 {'value': 62.0, 'startGMT': 1698645928000},
 {'value': 67.0, 'startGMT': 1698646228000},
 {'value': 62.0, 'startGMT': 1698646528000},
 {'value': 69.0, 'startGMT': 1698646828000},
 {'value': 73.0, 'startGMT': 1698647128000},
 {'value': 68.0, 'startGMT': 1698647428000},
 {'value': 68.0, 'startGMT': 1698647728000},
 {'value': 77.0, 'startGMT': 1698648028000},
 {'value': 81.0, 'startGMT': 1698648328000},
 {'value': 72.0, 'startGMT': 1698648628000},
 {'value': 67.0, 'startGMT': 1698648928000},
 {'value': 66.0, 'startGMT': 1698649228000},
 {'value': 60.0, 'startGMT': 1698649528000},
 {'value': 75.0, 'startGMT': 1698649828000},
 {'value': 74.0, 'startGMT': 1698650128000},
 {'value': 87.0, 'startGMT': 1698650428000},
 {'value': 79.0, 'startGMT': 1698650728000},
 {'value': 78.0, 'startGMT': 1698651028000},
 {'value': 77.0, 'startGMT': 1698651328000},
 {'value': 70.0, 'startGMT': 1698651628000},
 {'value': 72.0, 'startGMT': 1698651928000},
 {'value': 85.0, 'startGMT': 1698652228000},
 {'value': 96.0, 'startGMT': 1698652528000},
 {'value': 99.0, 'startGMT': 1698652828000},
 {'value': 87.0, 'startGMT': 1698653128000},
 {'value': 78.0, 'startGMT': 1698653428000},
 {'value': 71.0, 'startGMT': 1698653728000},
 {'value': 77.0, 'startGMT': 1698654028000},
 {'value': 58.0, 'startGMT': 1698654328000},
 {'value': 50.0, 'startGMT': 1698654628000},
 {'value': 74.0, 'startGMT': 1698654928000},
 {'value': 64.0, 'startGMT': 1698655228000},
 {'value': 73.0, 'startGMT': 1698655528000},
 {'value': 81.0, 'startGMT': 1698655828000},
 {'value': 67.0, 'startGMT': 1698656128000},
 {'value': 76.0, 'startGMT': 1698656428000},
 {'value': 70.0, 'startGMT': 1698656728000},
 {'value': 59.0, 'startGMT': 1698657028000},
 {'value': 60.0, 'startGMT': 1698657328000},
 {'value': 57.0, 'startGMT': 1698657628000},
 {'value': 55.0, 'startGMT': 1698657928000},
 {'value': 65.0, 'startGMT': 1698658228000},
 {'value': 67.0, 'startGMT': 1698658528000},
 {'value': 68.0, 'startGMT': 1698658828000},
 {'value': 52.0, 'startGMT': 1698659128000},
 {'value': 48.0, 'startGMT': 1698659428000}]

In [130]:
len(week_sleep_df['hrvData'][13])

76

In [52]:
week_sleep_df['hrvData']

0    [{'value': 87.0, 'startGMT': 1698368429000}, {...
1    [{'value': 55.0, 'startGMT': 1698456329000}, {...
2    [{'value': 56.0, 'startGMT': 1698542428000}, {...
3    [{'value': 65.0, 'startGMT': 1698629128000}, {...
Name: hrvData, dtype: object

In [65]:
a = pd.DataFrame.from_dict(week_sleep_df["hrvData"]).dropna(axis=0)

In [66]:
a

                                             hrvData
0  [{'value': 87.0, 'startGMT': 1698368429000}, {...
1  [{'value': 55.0, 'startGMT': 1698456329000}, {...
2  [{'value': 56.0, 'startGMT': 1698542428000}, {...
3  [{'value': 65.0, 'startGMT': 1698629128000}, {...

In [67]:
dfs = [pd.DataFrame(lst) for lst in a['hrvData'] if lst]

# Concatenate all the DataFrames to form the final DataFrame
final_df = pd.concat(dfs, ignore_index=True)

# Optionally, set "value" and "startGMT" as the index
final_df

     value       startGMT
0     87.0  1698368429000
1     75.0  1698368729000
2     72.0  1698369029000
3     70.0  1698369329000
4     71.0  1698369629000
..     ...            ...
399   65.0  1698658228000
400   67.0  1698658528000
401   68.0  1698658828000
402   52.0  1698659128000
403   48.0  1698659428000

[404 rows x 2 columns]

### sleepMovement

In [79]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['sleepMovement']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

                   startGMT                 endGMT  activityLevel
0     2023-10-26T23:57:00.0  2023-10-26T23:58:00.0       6.375683
1     2023-10-26T23:58:00.0  2023-10-26T23:59:00.0       6.009165
2     2023-10-26T23:59:00.0  2023-10-27T00:00:00.0       5.620718
3     2023-10-27T00:00:00.0  2023-10-27T00:01:00.0       5.215410
4     2023-10-27T00:01:00.0  2023-10-27T00:02:00.0       4.817395
...                     ...                    ...            ...
2501  2023-10-30T10:49:00.0  2023-10-30T10:50:00.0       4.442491
2502  2023-10-30T10:50:00.0  2023-10-30T10:51:00.0       4.747531
2503  2023-10-30T10:51:00.0  2023-10-30T10:52:00.0       5.108374
2504  2023-10-30T10:52:00.0  2023-10-30T10:53:00.0       5.496988
2505  2023-10-30T10:53:00.0  2023-10-30T10:54:00.0       5.890270

[2506 rows x 3 columns]

In [82]:
# Convert startGMT and endGMT to correct format

full_df["startGMT"] = [datetime.datetime.strptime(date, '%Y-%m-%dT%H:%M:%S.%f') for date in full_df["startGMT"]]
full_df["endGMT"] = [datetime.datetime.strptime(date, '%Y-%m-%dT%H:%M:%S.%f') for date in full_df["endGMT"]]

In [83]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2506 entries, 0 to 2505
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   startGMT       2506 non-null   datetime64[ns]
 1   endGMT         2506 non-null   datetime64[ns]
 2   activityLevel  2506 non-null   float64
dtypes: datetime64[ns](2), float64(1)
memory usage: 58.9 KB

In [84]:
full_df

                startGMT              endGMT  activityLevel
0    2023-10-26 23:57:00 2023-10-26 23:58:00       6.375683
1    2023-10-26 23:58:00 2023-10-26 23:59:00       6.009165
2    2023-10-26 23:59:00 2023-10-27 00:00:00       5.620718
3    2023-10-27 00:00:00 2023-10-27 00:01:00       5.215410
4    2023-10-27 00:01:00 2023-10-27 00:02:00       4.817395
...                  ...                 ...            ...
2501 2023-10-30 10:49:00 2023-10-30 10:50:00       4.442491
2502 2023-10-30 10:50:00 2023-10-30 10:51:00       4.747531
2503 2023-10-30 10:51:00 2023-10-30 10:52:00       5.108374
2504 2023-10-30 10:52:00 2023-10-30 10:53:00       5.496988
2505 2023-10-30 10:53:00 2023-10-30 10:54:00       5.890270

[2506 rows x 3 columns]

Data collected in 1 min interval

### sleepLevels

In [101]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['sleepLevels']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

                  startGMT                 endGMT  activityLevel
0    2023-10-27T00:57:00.0  2023-10-27T01:03:00.0            1.0
1    2023-10-27T01:03:00.0  2023-10-27T01:47:00.0            0.0
2    2023-10-27T01:47:00.0  2023-10-27T01:58:00.0            1.0
3    2023-10-27T01:58:00.0  2023-10-27T02:14:00.0            2.0
4    2023-10-27T02:14:00.0  2023-10-27T02:15:00.0            3.0
..                     ...                    ...            ...
103  2023-10-30T07:10:00.0  2023-10-30T08:05:00.0            1.0
104  2023-10-30T08:05:00.0  2023-10-30T08:49:00.0            2.0
105  2023-10-30T08:49:00.0  2023-10-30T08:52:00.0            3.0
106  2023-10-30T08:52:00.0  2023-10-30T09:37:00.0            1.0
107  2023-10-30T09:37:00.0  2023-10-30T09:54:00.0            2.0

[108 rows x 3 columns]

In [88]:
# Convert startGMT and endGMT to correct format

full_df["startGMT"] = [datetime.datetime.strptime(date, '%Y-%m-%dT%H:%M:%S.%f') for date in full_df["startGMT"]]
full_df["endGMT"] = [datetime.datetime.strptime(date, '%Y-%m-%dT%H:%M:%S.%f') for date in full_df["endGMT"]]
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   startGMT       108 non-null    datetime64[ns]
 1   endGMT         108 non-null    datetime64[ns]
 2   activityLevel  108 non-null    float64
dtypes: datetime64[ns](2), float64(1)
memory usage: 2.7 KB

In [89]:
full_df

               startGMT              endGMT  activityLevel
0   2023-10-27 00:57:00 2023-10-27 01:03:00            1.0
1   2023-10-27 01:03:00 2023-10-27 01:47:00            0.0
2   2023-10-27 01:47:00 2023-10-27 01:58:00            1.0
3   2023-10-27 01:58:00 2023-10-27 02:14:00            2.0
4   2023-10-27 02:14:00 2023-10-27 02:15:00            3.0
..                  ...                 ...            ...
103 2023-10-30 07:10:00 2023-10-30 08:05:00            1.0
104 2023-10-30 08:05:00 2023-10-30 08:49:00            2.0
105 2023-10-30 08:49:00 2023-10-30 08:52:00            3.0
106 2023-10-30 08:52:00 2023-10-30 09:37:00            1.0
107 2023-10-30 09:37:00 2023-10-30 09:54:00            2.0

[108 rows x 3 columns]

Data collected in rregular time interval

In [102]:
full_df.activityLevel.unique()

array([1., 0., 2., 3.])

### sleepRestlessMoments

In [90]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['sleepRestlessMoments']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

     value       startGMT
0        1  1698368400000
1        1  1698369480000
2        1  1698370920000
3        1  1698371280000
4        1  1698372000000
..     ...            ...
170      1  1698654840000
171      1  1698657900000
172      1  1698658800000
173      1  1698658980000
174      1  1698659520000

[175 rows x 2 columns]

In [91]:
full_df['Real Time'] = [datetime.datetime.fromtimestamp(i) for i in full_df["startGMT"] / 1000]
full_df

     value       startGMT           Real Time
0        1  1698368400000 2023-10-27 03:00:00
1        1  1698369480000 2023-10-27 03:18:00
2        1  1698370920000 2023-10-27 03:42:00
3        1  1698371280000 2023-10-27 03:48:00
4        1  1698372000000 2023-10-27 04:00:00
..     ...            ...                 ...
170      1  1698654840000 2023-10-30 09:34:00
171      1  1698657900000 2023-10-30 10:25:00
172      1  1698658800000 2023-10-30 10:40:00
173      1  1698658980000 2023-10-30 10:43:00
174      1  1698659520000 2023-10-30 10:52:00

[175 rows x 3 columns]

Data collected in rregular time interval

In [96]:
full_df.value.unique()

array([1, 2, 3], dtype=int64)

In [100]:
mask = full_df["value"] == 3

full_df[mask]

     value       startGMT           Real Time
120      3  1698562680000 2023-10-29 07:58:00

### wellnessEpochRespirationDataDTOList

In [103]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['wellnessEpochRespirationDataDTOList']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

       startTimeGMT  respirationValue
0     1698368220000              18.0
1     1698368280000              17.0
2     1698368400000              16.0
3     1698368520000              16.0
4     1698368640000              16.0
...             ...               ...
1012  1698659040000              13.0
1013  1698659160000              15.0
1014  1698659280000              14.0
1015  1698659400000              13.0
1016  1698659520000              12.0

[1017 rows x 2 columns]

In [105]:
full_df['Real Time'] = [datetime.datetime.fromtimestamp(i) for i in full_df["startTimeGMT"] / 1000]
full_df

       startTimeGMT  respirationValue           Real Time
0     1698368220000              18.0 2023-10-27 02:57:00
1     1698368280000              17.0 2023-10-27 02:58:00
2     1698368400000              16.0 2023-10-27 03:00:00
3     1698368520000              16.0 2023-10-27 03:02:00
4     1698368640000              16.0 2023-10-27 03:04:00
...             ...               ...                 ...
1012  1698659040000              13.0 2023-10-30 10:44:00
1013  1698659160000              15.0 2023-10-30 10:46:00
1014  1698659280000              14.0 2023-10-30 10:48:00
1015  1698659400000              13.0 2023-10-30 10:50:00
1016  1698659520000              12.0 2023-10-30 10:52:00

[1017 rows x 3 columns]

Time interval 1-2 minutes

In [106]:
full_df.respirationValue.unique()

array([18., 17., 16., 15., 14., 13., 12., 11., 10.,  9.])

### sleepHeartRate

In [107]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['sleepHeartRate']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

      value       startGMT
0        53  1698368160000
1        49  1698368280000
2        50  1698368400000
3        50  1698368520000
4        51  1698368640000
...     ...            ...
1011     57  1698659040000
1012     61  1698659160000
1013     60  1698659280000
1014     70  1698659400000
1015     78  1698659520000

[1016 rows x 2 columns]

In [108]:
full_df['Real Time'] = [datetime.datetime.fromtimestamp(i) for i in full_df["startGMT"] / 1000]
full_df

      value       startGMT           Real Time
0        53  1698368160000 2023-10-27 02:56:00
1        49  1698368280000 2023-10-27 02:58:00
2        50  1698368400000 2023-10-27 03:00:00
3        50  1698368520000 2023-10-27 03:02:00
4        51  1698368640000 2023-10-27 03:04:00
...     ...            ...                 ...
1011     57  1698659040000 2023-10-30 10:44:00
1012     61  1698659160000 2023-10-30 10:46:00
1013     60  1698659280000 2023-10-30 10:48:00
1014     70  1698659400000 2023-10-30 10:50:00
1015     78  1698659520000 2023-10-30 10:52:00

[1016 rows x 3 columns]

2 min time interval

### sleepStress

In [113]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['sleepStress']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

     value       startGMT
0        6  1698368040000
1        4  1698368220000
2        6  1698368400000
3        8  1698368580000
4        5  1698368760000
..     ...            ...
674     23  1698658740000
675     24  1698658920000
676     23  1698659100000
677     44  1698659280000
678     77  1698659460000

[679 rows x 2 columns]

In [114]:
full_df['Real Time'] = [datetime.datetime.fromtimestamp(i) for i in full_df["startGMT"] / 1000]
full_df

     value       startGMT           Real Time
0        6  1698368040000 2023-10-27 02:54:00
1        4  1698368220000 2023-10-27 02:57:00
2        6  1698368400000 2023-10-27 03:00:00
3        8  1698368580000 2023-10-27 03:03:00
4        5  1698368760000 2023-10-27 03:06:00
..     ...            ...                 ...
674     23  1698658740000 2023-10-30 10:39:00
675     24  1698658920000 2023-10-30 10:42:00
676     23  1698659100000 2023-10-30 10:45:00
677     44  1698659280000 2023-10-30 10:48:00
678     77  1698659460000 2023-10-30 10:51:00

[679 rows x 3 columns]

3 mins interval

In [115]:
full_df.value.unique()

array([ 6,  4,  8,  5,  7, 11,  9, 10, 13, 12, 15, 17, 32, 25, 23, 43, 47,
       29, 16, 24, 19, 18, 14, 20, 37, 21, 27, 34, 22,  2,  3, 36, 61, 31,
       28, 73, 67, 62, 45, 35, 30, 51, 48, 26, 33, -1, 44, 77],
      dtype=int64)

### sleepBodyBattery

In [116]:
flattened_dfs = [pd.json_normalize(item) for item in week_sleep_df['sleepBodyBattery']]
full_df = pd.concat(flattened_dfs, ignore_index=True)
full_df

     value       startGMT
0       16  1698368040000
1       16  1698368220000
2       16  1698368400000
3       16  1698368580000
4       17  1698368760000
..     ...            ...
674     94  1698658740000
675     94  1698658920000
676     94  1698659100000
677     94  1698659280000
678     94  1698659460000

[679 rows x 2 columns]

In [117]:
full_df['Real Time'] = [datetime.datetime.fromtimestamp(i) for i in full_df["startGMT"] / 1000]
full_df

     value       startGMT           Real Time
0       16  1698368040000 2023-10-27 02:54:00
1       16  1698368220000 2023-10-27 02:57:00
2       16  1698368400000 2023-10-27 03:00:00
3       16  1698368580000 2023-10-27 03:03:00
4       17  1698368760000 2023-10-27 03:06:00
..     ...            ...                 ...
674     94  1698658740000 2023-10-30 10:39:00
675     94  1698658920000 2023-10-30 10:42:00
676     94  1698659100000 2023-10-30 10:45:00
677     94  1698659280000 2023-10-30 10:48:00
678     94  1698659460000 2023-10-30 10:51:00

[679 rows x 3 columns]

3 min time intervals

### dailysleepDTO

In [118]:
expanded_df

,id,userProfilePK,calendarDate,sleepTimeSeconds,napTimeSeconds,sleepWindowConfirmed,sleepWindowConfirmationType,sleepStartTimestampGMT,sleepEndTimestampGMT,sleepStartTimestampLocal,...,sleepScores.lightPercentage.optimalStart,sleepScores.lightPercentage.optimalEnd,sleepScores.lightPercentage.idealStartInSeconds,sleepScores.lightPercentage.idealEndInSeconds,sleepScores.deepPercentage.value,sleepScores.deepPercentage.qualifierKey,sleepScores.deepPercentage.optimalStart,sleepScores.deepPercentage.optimalEnd,sleepScores.deepPercentage.idealStartInSeconds,sleepScores.deepPercentage.idealEndInSeconds
0,1698368220000,116790105,2023-10-27,25260,0,True,enhanced_confirmed_final,1698368220000,1698395700000,1698375420000,...,30.0,64.0,7578.0,16166.4,20,EXCELLENT,16.0,33.0,4041.6,8335.8
1,1698456060000,116790105,2023-10-28,31620,0,True,enhanced_confirmed_final,1698456060000,1698491100000,1698463260000,...,30.0,64.0,9486.0,20236.8,16,FAIR,16.0,33.0,5059.2,10434.6
2,1698542340000,116790105,2023-10-29,27780,0,True,enhanced_confirmed_final,1698542340000,1698570660000,1698545940000,...,30.0,64.0,8334.0,17779.2,19,EXCELLENT,16.0,33.0,4444.8,9167.4
3,1698628920000,116790105,2023-10-30,29940,0,True,enhanced_confirmed_final,1698628920000,1698659640000,1698632520000,...,30.0,64.0,8982.0,19161.6,20,EXCELLENT,16.0,33.0,4790.4,9880.2

We have a row that represent a date --> good

#### convert column with time to "understandable" form

In [119]:
expanded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 65 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   id                                               4 non-null      int64
 1   userProfilePK                                    4 non-null      int64
 2   calendarDate                                     4 non-null      object
 3   sleepTimeSeconds                                 4 non-null      int64
 4   napTimeSeconds                                   4 non-null      int64
 5   sleepWindowConfirmed                             4 non-null      bool
 6   sleepWindowConfirmationType                      4 non-null      object
 7   sleepStartTimestampGMT                           4 non-null      int64
 8   sleepEndTimestampGMT                             4 non-null      int64
 9   sleepStartTimestampLocal                         4 non-null      int64
 10  sleepEndTimestampLocal                           4 non-null      int64
 11  autoSleepStartTimestampGMT                       0 non-null      object
 12  autoSleepEndTimestampGMT                         0 non-null      object
 13  sleepQualityTypePK                               0 non-null      object
 14  sleepResultTypePK                                0 non-null      object
 15  unmeasurableSleepSeconds                         4 non-null      int64
 16  deepSleepSeconds                                 4 non-null      int64
 17  lightSleepSeconds                                4 non-null      int64
 18  remSleepSeconds                                  4 non-null      int64
 19  awakeSleepSeconds                                4 non-null      int64
 20  deviceRemCapable                                 4 non-null      bool
 21  retro                                            4 non-null      bool
 22  sleepFromDevice                                  4 non-null      bool
 23  averageRespirationValue                          4 non-null      float64
 24  lowestRespirationValue                           4 non-null      float64
 25  highestRespirationValue                          4 non-null      float64
 26  awakeCount                                       4 non-null      int64
 27  avgSleepStress                                   4 non-null      float64
 28  ageGroup                                         4 non-null      object
 29  sleepScoreFeedback                               4 non-null      object
 30  sleepScoreInsight                                4 non-null      object
 31  sleepScorePersonalizedInsight                    4 non-null      object
 32  sleepVersion                                     4 non-null      int64
 33  sleepScores.totalDuration.qualifierKey           4 non-null      object
 34  sleepScores.totalDuration.optimalStart           4 non-null      float64
 35  sleepScores.totalDuration.optimalEnd             4 non-null      float64
 36  sleepScores.stress.qualifierKey                  4 non-null      object
 37  sleepScores.stress.optimalStart                  4 non-null      float64
 38  sleepScores.stress.optimalEnd                    4 non-null      float64
 39  sleepScores.awakeCount.qualifierKey              4 non-null      object
 40  sleepScores.awakeCount.optimalStart              4 non-null      float64
 41  sleepScores.awakeCount.optimalEnd                4 non-null      float64
 42  sleepScores.overall.value                        4 non-null      int64
 43  sleepScores.overall.qualifierKey                 4 non-null      object
 44  sleepScores.remPercentage.value                  4 non-null      int64
 45  sleepScores.remPercentage.qualifierKey           4 non-null      object
 46  sleepScores.remPercentage.optimalStart           4 non-null      float64
 47  sleepScores.remPercentage.optimalEnd             4 non-null      float64
 48  sleepScores.remPercentage.idealStartInSeconds    4 non-null      float64
 49  sleepScores.remPercentage.idealEndInSeconds      4 non-null      float64
 50  sleepScores.restlessness.qualifierKey            4 non-null      object
 51  sleepScores.restlessness.optimalStart            4 non-null      float64
 52  sleepScores.restlessness.optimalEnd              4 non-null      float64
 53  sleepScores.lightPercentage.value                4 non-null      int64
 54  sleepScores.lightPercentage.qualifierKey         4 non-null      object
 55  sleepScores.lightPercentage.optimalStart         4 non-null      float64
 56  sleepScores.lightPercentage.optimalEnd           4 non-null      float64
 57  sleepScores.lightPercentage.idealStartInSeconds  4 non-null      float64
 58  sleepScores.lightPercentage.idealEndInSeconds    4 non-null      float64
 59  sleepScores.deepPercentage.value                 4 non-null      int64
 60  sleepScores.deepPercentage.qualifierKey          4 non-null      object
 61  sleepScores.deepPercentage.optimalStart          4 non-null      float64
 62  sleepScores.deepPercentage.optimalEnd            4 non-null      float64
 63  sleepScores.deepPercentage.idealStartInSeconds   4 non-null      float64
 64  sleepScores.deepPercentage.idealEndInSeconds     4 non-null      float64
dtypes: bool(4), float64(24), int64(19), object(18)
memory usage: 2.1+ KB

In [128]:
expanded_df.iloc[:,:20]

,id,userProfilePK,calendarDate,sleepTimeSeconds,napTimeSeconds,sleepWindowConfirmed,sleepWindowConfirmationType,sleepStartTimestampGMT,sleepEndTimestampGMT,sleepStartTimestampLocal,sleepEndTimestampLocal,autoSleepStartTimestampGMT,autoSleepEndTimestampGMT,sleepQualityTypePK,sleepResultTypePK,unmeasurableSleepSeconds,deepSleepSeconds,lightSleepSeconds,remSleepSeconds,awakeSleepSeconds
0,1698368220000,116790105,2023-10-27,25260,0,True,enhanced_confirmed_final,1698368220000,1698395700000,1698375420000,1698402900000,None,None,None,None,0,4980,13860,6420,2220
1,1698456060000,116790105,2023-10-28,31620,0,True,enhanced_confirmed_final,1698456060000,1698491100000,1698463260000,1698498300000,None,None,None,None,0,4920,22140,4560,3420
2,1698542340000,116790105,2023-10-29,27780,0,True,enhanced_confirmed_final,1698542340000,1698570660000,1698545940000,1698574260000,None,None,None,None,0,5400,15720,6660,540
3,1698628920000,116790105,2023-10-30,29940,0,True,enhanced_confirmed_final,1698628920000,1698659640000,1698632520000,1698663240000,None,None,None,None,0,6000,16740,7200,780

In [130]:
expanded_df.iloc[:,20:40]

,deviceRemCapable,retro,sleepFromDevice,averageRespirationValue,lowestRespirationValue,highestRespirationValue,awakeCount,avgSleepStress,ageGroup,sleepScoreFeedback,sleepScoreInsight,sleepScorePersonalizedInsight,sleepVersion,sleepScores.totalDuration.qualifierKey,sleepScores.totalDuration.optimalStart,sleepScores.totalDuration.optimalEnd,sleepScores.stress.qualifierKey,sleepScores.stress.optimalStart,sleepScores.stress.optimalEnd,sleepScores.awakeCount.qualifierKey
0,True,False,True,15.0,12.0,18.0,2,19.0,ADULT,POSITIVE_REFRESHING,POSITIVE_LATE_BED_TIME,NOT_AVAILABLE,2,FAIR,28800.0,28800.0,FAIR,0.0,15.0,FAIR
1,True,False,True,14.0,10.0,17.0,3,16.0,ADULT,NEGATIVE_LONG_BUT_DISCONTINUOUS,NONE,NOT_AVAILABLE,2,EXCELLENT,28800.0,28800.0,FAIR,0.0,15.0,POOR
2,True,False,True,15.0,12.0,18.0,0,15.0,ADULT,POSITIVE_OPTIMAL_STRUCTURE,NONE,NOT_AVAILABLE,2,EXCELLENT,28800.0,28800.0,GOOD,0.0,15.0,EXCELLENT
3,True,False,True,14.0,9.0,18.0,1,13.0,ADULT,POSITIVE_OPTIMAL_STRUCTURE,NONE,NOT_AVAILABLE,2,EXCELLENT,28800.0,28800.0,EXCELLENT,0.0,15.0,GOOD

In [131]:
expanded_df.iloc[:,40:60]

,sleepScores.awakeCount.optimalStart,sleepScores.awakeCount.optimalEnd,sleepScores.overall.value,sleepScores.overall.qualifierKey,sleepScores.remPercentage.value,sleepScores.remPercentage.qualifierKey,sleepScores.remPercentage.optimalStart,sleepScores.remPercentage.optimalEnd,sleepScores.remPercentage.idealStartInSeconds,sleepScores.remPercentage.idealEndInSeconds,sleepScores.restlessness.qualifierKey,sleepScores.restlessness.optimalStart,sleepScores.restlessness.optimalEnd,sleepScores.lightPercentage.value,sleepScores.lightPercentage.qualifierKey,sleepScores.lightPercentage.optimalStart,sleepScores.lightPercentage.optimalEnd,sleepScores.lightPercentage.idealStartInSeconds,sleepScores.lightPercentage.idealEndInSeconds,sleepScores.deepPercentage.value
0,0.0,1.0,77,FAIR,25,EXCELLENT,21.0,31.0,5304.6,7830.6,FAIR,0.0,5.0,55,EXCELLENT,30.0,64.0,7578.0,16166.4,20
1,0.0,1.0,74,FAIR,14,FAIR,21.0,31.0,6640.2,9802.2,POOR,0.0,5.0,70,FAIR,30.0,64.0,9486.0,20236.8,16
2,0.0,1.0,91,EXCELLENT,24,EXCELLENT,21.0,31.0,5833.8,8611.8,EXCELLENT,0.0,5.0,57,EXCELLENT,30.0,64.0,8334.0,17779.2,19
3,0.0,1.0,94,EXCELLENT,24,EXCELLENT,21.0,31.0,6287.4,9281.4,GOOD,0.0,5.0,56,EXCELLENT,30.0,64.0,8982.0,19161.6,20

In [133]:
expanded_df.iloc[:,60:]

,sleepScores.deepPercentage.qualifierKey,sleepScores.deepPercentage.optimalStart,sleepScores.deepPercentage.optimalEnd,sleepScores.deepPercentage.idealStartInSeconds,sleepScores.deepPercentage.idealEndInSeconds
0,EXCELLENT,16.0,33.0,4041.6,8335.8
1,FAIR,16.0,33.0,5059.2,10434.6
2,EXCELLENT,16.0,33.0,4444.8,9167.4
3,EXCELLENT,16.0,33.0,4790.4,9880.2

In [139]:
expanded_df['sleepStartTimestampGMT'] = [datetime.datetime.fromtimestamp(i) 
                                         for i in expanded_df["sleepStartTimestampGMT"] / 1000]
expanded_df['sleepEndTimestampGMT'] = [datetime.datetime.fromtimestamp(i) 
                                         for i in expanded_df["sleepEndTimestampGMT"] / 1000]
expanded_df['sleepStartTimestampLocal'] = [datetime.datetime.fromtimestamp(i) 
                                         for i in expanded_df["sleepStartTimestampLocal"] / 1000]
expanded_df['sleepEndTimestampLocal'] = [datetime.datetime.fromtimestamp(i) 
                                         for i in expanded_df["sleepEndTimestampLocal"] / 1000]

In [142]:
expanded_df.iloc[:,:11]

,id,userProfilePK,calendarDate,sleepTimeSeconds,napTimeSeconds,sleepWindowConfirmed,sleepWindowConfirmationType,sleepStartTimestampGMT,sleepEndTimestampGMT,sleepStartTimestampLocal,sleepEndTimestampLocal
0,1698368220000,116790105,2023-10-27,25260,0,True,enhanced_confirmed_final,2023-10-27 02:57:00,2023-10-27 10:35:00,2023-10-27 04:57:00,2023-10-27 12:35:00
1,1698456060000,116790105,2023-10-28,31620,0,True,enhanced_confirmed_final,2023-10-28 03:21:00,2023-10-28 13:05:00,2023-10-28 05:21:00,2023-10-28 15:05:00
2,1698542340000,116790105,2023-10-29,27780,0,True,enhanced_confirmed_final,2023-10-29 02:19:00,2023-10-29 10:11:00,2023-10-29 03:19:00,2023-10-29 11:11:00
3,1698628920000,116790105,2023-10-30,29940,0,True,enhanced_confirmed_final,2023-10-30 02:22:00,2023-10-30 10:54:00,2023-10-30 03:22:00,2023-10-30 11:54:00